apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ichsan-setiawan-gateway-api
spec:
  selector:
    istio: istio-ingressgateway
  servers:
  - hosts:
    - "*.nip.io"
    port:
      name: http
      number: 80
      protocol: HTTP
    # tls:
    #   httpsRedirect: true