apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: validation
spec:
  gateways:
  - ichsan-setiawan-gateway-api
  hosts:
  - 34-171-120-56.xip.io
  http:
  - match:
    - uri:
        prefix: /validate
    route:
    - destination:
        host: validation
        port:
          number: 3000